/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import java.io.*;
import java.util.*;

class Even_Fibonnaci_Numbers {
	public static void main(String[] args) {
		long firstNumber = 0;	// storing n-2
		long secondNumber = 1;	// storing n-1
		long currentValue = 1;	// storing n

		long sum = 0;	// sum of all even values
		long end = 4000000;	// end at four million

		while(currentValue < end) {	// iterate until end
			// shift all values over one
			firstNumber = secondNumber;
			secondNumber = currentValue;

			currentValue = firstNumber + secondNumber;	// find new currentValue

			if(currentValue % 2 == 0) {	// check divisibility
				sum += currentValue;	// if divisible by 2, add to sum
			}
		}

		System.out.println("The sum of all even terms in the fibonacci sequence whose values do not exceed four million is: " + sum);
	}
}