/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

import java.io.*;
import java.util.*;

class Even_Fibonnaci_Numbers {
	public static void main(String[] args) {
		long firstNumber = 0;
		long secondNumber = 1;
		long currentValue = 0;

		long sum = 0;
		long end = 4000000;	// end at four million

		while(currentValue < end) {
			firstNumber = secondNumber;
			secondNumber = currentValue;

			currentValue = firstNumber + secondNumber;

			if(currentValue%2 == 0) {
				sum += currentValue;
			}
		}

		System.out.println(sum);
	}
}